### ISSUE TITLE
Use NetCorePluginManager in a service

### ISSUE THREAD

**Issue by large** [k3ldar/.NetCorePluginManager#107]
**Describe the bug**
Using the pluginmanager in a windows services makes it crash after it is depolyed.

**To Reproduce**
See this link on how to create a Windows service for the pluginmanager:
https://dzone.com/articles/running-aspnet-core-application-as-windows-service

Compile and deploy to a directory, register det service to that directory and try to start service.

Crashinfo from eventviewer (line 30 is just a comment in my code, wrong I guess because of deployed files):
Application: serverservice.exe
CoreCLR Version: 4.700.19.60701
.NET Core Version: 3.1.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.PluginManager.PluginManagerService.Finalise()
   at serverservice.Program.Main(String[] args) in C:\repos\serverservice\Program.cs:line 30

**Expected behavior**
Pluginmanager should work even in a windows service ;)

**Desktop (please complete the following information):**
 - OS: Windows only(!)

**Additional context**
When running as a service the "GetCurrentDirectory" function returns %windir%\system32 always.
Check out M$ way to handle it https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&tabs=visual-studio
and
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&tabs=visual-studio#current-directory-and-content-root

I suspect that the configuration use the GetCurrentDirectory(): https://github.com/k3ldar/.NetCorePluginManager/blob/03850de2a045a3306c7be5b3f3d09de50ae9bcad/PluginManager/src/Configuration/PluginManagerConfiguration.cs#L86 and it will fail.

**Comment by large** [comment]
I have investigated and found a solution that made everything work.

```
            var isService = !(Debugger.IsAttached || args.Contains("--console"));
            var pathToContentRoot = Directory.GetCurrentDirectory();

            if (isService)
            {
                var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
                pathToContentRoot = Path.GetDirectoryName(pathToExe);
                Directory.SetCurrentDirectory(pathToContentRoot);
            }
```
Every GetCurrentDirectory(); after SetCurrentDirectory() is set will return the value you set.
So everything works, nothing to see here ;) Dot net core as service was a nice feature :)

**Comment by k3ldar** [comment]
I can see your point here, The path is used when loading configuration data from appsettings.json.  I will get this fixed, however there is an easy work around for the meantime, there are 2 different signatures for the method PluginManagerService.Initialise 

One of the methods has no parameters, the other you can pass in an initialised PluginManagerConfiguration class, if you create an instance of this class, you can manually set the CurrentPath to the correct path using your fix above. the CurrentPath property is public set and get and was designed to allow users to use a custom directory for obtaining configuration data :-)

On a side note, are you using this as a net core web application service or just using the plugin manager for a normal service?  I ask because I recently split the core PluginManager element from the AspNetCore.PluginManager class with the intention of having it as a base plugin manager for different kinds of plugins, i.e. winform, services etc and creating specific plugin manager for those scenarios (this won't be quick as my back log is quite busy) but would be interesting to know :-)

**Comment by large** [comment]
I use it as a web application service using Kestrel. Worked like a charm :)
My project these days are admin interface to a SMTP-server (.Net only) I've created earlier.

SMTP server already used plugins (bayes, ipblock, dnsbl etc) based on my simple design. With your framework the admin / users can enjoy a gui too 👍

**Comment by k3ldar** [comment]
Now I can see why embedded views are important, nice use case :-)
